### ISSUE TITLE
Templates print at different size when using badge-printer

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/badge-printer#1]
I set this up on my home computer to test the new label printer, and I noticed that if I print from the application the result is much smaller (larger margins?) than when I print directly from Inkscape.  I wonder if this is related to the issues with the badge printer not printing properly.

**Comment by domstoppable** [comment]
The original templates were designed to render 300 DPI rasters which could then be printed. The new print system using Inkscape, so the templates have been resized to match the actual physical dimensions.

PS - it, in fact, was an issue with the badge printer not printing correctly. There were other issues as well (like margins).
