### ISSUE TITLE
Going through the print dialog every time is tedious

### ISSUE THREAD

**Issue by Rowbotronics** [MakeICT/badge-printer#3]
Going through the print dialog every time is tedious. It would be much simpler if hitting "print and log" would just immediately print to the appropriate printer. It would save a lot of time when needing to print a lot of nametags quickly. Printer settings could be saved on a per-template basis. They shouldn't need to be changed often, if ever.

**Comment by Rowbotronics** [comment]
I added a new branch to work on this feature. I mostly just copied what James had done with the other application, which calls inkscape on the command line to generate a ps file and then uses lpr to print. It needs some work on being made configurable, but it does also work around the issue in #2.

**Comment by Rowbotronics** [comment]
Works great with the label printer, but not so much with the Zebra.

**Comment by domstoppable** [comment]
Thanks! I tweaked and merged your changes. The Quick Print™ workflow allows the user to simply hit "Enter" after updating appropriate fields. The job is sent to the printer and focus is moved to the first template field so the next changes can be applied.

The only limiting factor now is the speed of the print spooler and the printer itself.
